
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db
  mongo-express:
   image: mongo-express
   container_name: mongo-express
   ports:
    - "8081:8081"
   environment:
    ME_CONFIG_MONGODB_SERVER: mongo
    ME_CONFIG_MONGODB_PORT: 27017
    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    ME_CONFIG_MONGODB_ADMINPASSWORD: password
   depends_on:
    - mongo
   networks:
    - my_network

networks:
  my_network:
    driver: bridge


volumes:
  mongo_data:
    driver: local
    